config/routes.rb
Rails.application.routes.draw do


  



  devise_for :logins
  
  resources :tipo_notificaciones
  resources :notificaciones
  resources :estados
  resources :adjuntos
  resources :parametros
  resources :tipo_solicitudes
  resources :tipo_seguimientos
  resources :seguimientos
  resources :permisos
  resources :solicituds
  resources :areas
  resources :roles
  resources :users

  get 'welcome/index'
  post 'users/index'
  post 'solicituds/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adjunto.rb
class Adjunto < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/notificacione.rb
class Notificacione < ApplicationRecord
end

app/models/parametro.rb
class Parametro < ApplicationRecord
end

app/models/permiso.rb
class Permiso < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/seguimiento.rb
class Seguimiento < ApplicationRecord
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
end

app/models/tipo_seguimiento.rb
class TipoSeguimiento < ApplicationRecord
end

app/models/tipo_solicitude.rb
class TipoSolicitude < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/permisos_controller.rb
class PermisosController < ApplicationController
  before_action :set_permiso, only: [:show, :edit, :update, :destroy]

  # GET /permisos
  # GET /permisos.json
  def index
    @permisos = Permiso.all
  end

  # GET /permisos/1
  # GET /permisos/1.json
  def show
  end

  # GET /permisos/new
  def new
    @permiso = Permiso.new
  end

  # GET /permisos/1/edit
  def edit
  end

  # POST /permisos
  # POST /permisos.json
  def create
    @permiso = Permiso.new(permiso_params)

    respond_to do |format|
      if @permiso.save
        format.html { redirect_to @permiso, notice: 'Permiso was successfully created.' }
        format.json { render :show, status: :created, location: @permiso }
      else
        format.html { render :new }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permisos/1
  # PATCH/PUT /permisos/1.json
  def update
    respond_to do |format|
      if @permiso.update(permiso_params)
        format.html { redirect_to @permiso, notice: 'Permiso was successfully updated.' }
        format.json { render :show, status: :ok, location: @permiso }
      else
        format.html { render :edit }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permisos/1
  # DELETE /permisos/1.json
  def destroy
    @permiso.destroy
    respond_to do |format|
      format.html { redirect_to permisos_url, notice: 'Permiso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permiso
      @permiso = Permiso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permiso_params
      params.require(:permiso).permit(:tipo_permiso, :descripcion)
    end
end

app/helpers/adjuntos_helper.rb
module AdjuntosHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/parametros_helper.rb
module ParametrosHelper
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/permisos/_form.html.erb
<%= form_with(model: permiso, local: true) do |form| %>
  <% if permiso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permiso.errors.count, "error") %> prohibited this permiso from being saved:</h2>

      <ul>
      <% permiso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo_permiso %>
    <%= form.text_field :tipo_permiso %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/permisos/edit.html.erb
<h1>Editing Permiso</h1>

<%= render 'form', permiso: @permiso %>

<%= link_to 'Show', @permiso %> |
<%= link_to 'Back', permisos_path %>

app/views/permisos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permisos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo permiso</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permisos.each do |permiso| %>
      <tr>
        <td><%= permiso.tipo_permiso %></td>
        <td><%= permiso.descripcion %></td>
        <td><%= link_to 'Show', permiso %></td>
        <td><%= link_to 'Edit', edit_permiso_path(permiso) %></td>
        <td><%= link_to 'Destroy', permiso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permiso', new_permiso_path %>

app/views/permisos/new.html.erb
<h1>New Permiso</h1>

<%= render 'form', permiso: @permiso %>

<%= link_to 'Back', permisos_path %>

app/views/permisos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo permiso:</strong>
  <%= @permiso.tipo_permiso %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @permiso.descripcion %>
</p>

<%= link_to 'Edit', edit_permiso_path(@permiso) %> |
<%= link_to 'Back', permisos_path %>