config/routes.rb
Rails.application.routes.draw do


  



  devise_for :logins
  
  resources :tipo_notificaciones
  resources :notificaciones
  resources :estados
  resources :adjuntos
  resources :parametros
  resources :tipo_solicitudes
  resources :tipo_seguimientos
  resources :seguimientos
  resources :permisos
  resources :solicituds
  resources :areas
  resources :roles
  resources :users

  get 'welcome/index'
  post 'users/index'
  post 'solicituds/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adjunto.rb
class Adjunto < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/notificacione.rb
class Notificacione < ApplicationRecord
end

app/models/parametro.rb
class Parametro < ApplicationRecord
end

app/models/permiso.rb
class Permiso < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/seguimiento.rb
class Seguimiento < ApplicationRecord
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
end

app/models/tipo_seguimiento.rb
class TipoSeguimiento < ApplicationRecord
end

app/models/tipo_solicitude.rb
class TipoSolicitude < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/seguimientos_controller.rb
class SeguimientosController < ApplicationController
  before_action :set_seguimiento, only: [:show, :edit, :update, :destroy]

  # GET /seguimientos
  # GET /seguimientos.json
  def index
    @seguimientos = Seguimiento.all
  end

  # GET /seguimientos/1
  # GET /seguimientos/1.json
  def show
  end

  # GET /seguimientos/new
  def new
    @seguimiento = Seguimiento.new
  end

  # GET /seguimientos/1/edit
  def edit
  end

  # POST /seguimientos
  # POST /seguimientos.json
  def create
    @seguimiento = Seguimiento.new(seguimiento_params)

    respond_to do |format|
      if @seguimiento.save
        format.html { redirect_to @seguimiento, notice: 'Seguimiento was successfully created.' }
        format.json { render :show, status: :created, location: @seguimiento }
      else
        format.html { render :new }
        format.json { render json: @seguimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seguimientos/1
  # PATCH/PUT /seguimientos/1.json
  def update
    respond_to do |format|
      if @seguimiento.update(seguimiento_params)
        format.html { redirect_to @seguimiento, notice: 'Seguimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @seguimiento }
      else
        format.html { render :edit }
        format.json { render json: @seguimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seguimientos/1
  # DELETE /seguimientos/1.json
  def destroy
    @seguimiento.destroy
    respond_to do |format|
      format.html { redirect_to seguimientos_url, notice: 'Seguimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seguimiento
      @seguimiento = Seguimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seguimiento_params
      params.require(:seguimiento).permit(:descripcion, :fecha, :hora, :id_tipo_seguimiento)
    end
end

app/helpers/adjuntos_helper.rb
module AdjuntosHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/parametros_helper.rb
module ParametrosHelper
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/seguimientos_helper.rb
module SeguimientosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/seguimientos/_form.html.erb
<%= form_with(model: seguimiento, local: true) do |form| %>
  <% if seguimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seguimiento.errors.count, "error") %> prohibited this seguimiento from being saved:</h2>

      <ul>
      <% seguimiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :hora %>
    <%= form.time_select :hora %>
  </div>

  <div class="field">
    <%= form.label :id_tipo_seguimiento %>
    <%= form.number_field :id_tipo_seguimiento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seguimientos/edit.html.erb
<h1>Editing Seguimiento</h1>

<%= render 'form', seguimiento: @seguimiento %>

<%= link_to 'Show', @seguimiento %> |
<%= link_to 'Back', seguimientos_path %>

app/views/seguimientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seguimientos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Id tipo seguimiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seguimientos.each do |seguimiento| %>
      <tr>
        <td><%= seguimiento.descripcion %></td>
        <td><%= seguimiento.fecha %></td>
        <td><%= seguimiento.hora %></td>
        <td><%= seguimiento.id_tipo_seguimiento %></td>
        <td><%= link_to 'Show', seguimiento %></td>
        <td><%= link_to 'Edit', edit_seguimiento_path(seguimiento) %></td>
        <td><%= link_to 'Destroy', seguimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seguimiento', new_seguimiento_path %>

app/views/seguimientos/new.html.erb
<h1>New Seguimiento</h1>

<%= render 'form', seguimiento: @seguimiento %>

<%= link_to 'Back', seguimientos_path %>

app/views/seguimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @seguimiento.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @seguimiento.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @seguimiento.hora %>
</p>

<p>
  <strong>Id tipo seguimiento:</strong>
  <%= @seguimiento.id_tipo_seguimiento %>
</p>

<%= link_to 'Edit', edit_seguimiento_path(@seguimiento) %> |
<%= link_to 'Back', seguimientos_path %>