config/routes.rb
Rails.application.routes.draw do


  



  devise_for :logins
  
  resources :tipo_notificaciones
  resources :notificaciones
  resources :estados
  resources :adjuntos
  resources :parametros
  resources :tipo_solicitudes
  resources :tipo_seguimientos
  resources :seguimientos
  resources :permisos
  resources :solicituds
  resources :areas
  resources :roles
  resources :users

  get 'welcome/index'
  post 'users/index'
  post 'solicituds/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adjunto.rb
class Adjunto < ApplicationRecord
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/notificacione.rb
class Notificacione < ApplicationRecord
end

app/models/parametro.rb
class Parametro < ApplicationRecord
end

app/models/permiso.rb
class Permiso < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/seguimiento.rb
class Seguimiento < ApplicationRecord
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
end

app/models/tipo_seguimiento.rb
class TipoSeguimiento < ApplicationRecord
end

app/models/tipo_solicitude.rb
class TipoSolicitude < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/notificaciones_controller.rb
class NotificacionesController < ApplicationController
  before_action :set_notificacione, only: [:show, :edit, :update, :destroy]

  # GET /notificaciones
  # GET /notificaciones.json
  def index
    @notificaciones = Notificacione.all
  end

  # GET /notificaciones/1
  # GET /notificaciones/1.json
  def show
  end

  # GET /notificaciones/new
  def new
    @notificacione = Notificacione.new
  end

  # GET /notificaciones/1/edit
  def edit
  end

  # POST /notificaciones
  # POST /notificaciones.json
  def create
    @notificacione = Notificacione.new(notificacione_params)

    respond_to do |format|
      if @notificacione.save
        format.html { redirect_to @notificacione, notice: 'Notificacione was successfully created.' }
        format.json { render :show, status: :created, location: @notificacione }
      else
        format.html { render :new }
        format.json { render json: @notificacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notificaciones/1
  # PATCH/PUT /notificaciones/1.json
  def update
    respond_to do |format|
      if @notificacione.update(notificacione_params)
        format.html { redirect_to @notificacione, notice: 'Notificacione was successfully updated.' }
        format.json { render :show, status: :ok, location: @notificacione }
      else
        format.html { render :edit }
        format.json { render json: @notificacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notificaciones/1
  # DELETE /notificaciones/1.json
  def destroy
    @notificacione.destroy
    respond_to do |format|
      format.html { redirect_to notificaciones_url, notice: 'Notificacione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notificacione
      @notificacione = Notificacione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notificacione_params
      params.require(:notificacione).permit(:mensaje, :fecha, :id_tipo_notificacion)
    end
end

app/helpers/adjuntos_helper.rb
module AdjuntosHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/notificaciones_helper.rb
module NotificacionesHelper
end

app/helpers/parametros_helper.rb
module ParametrosHelper
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/notificaciones/_form.html.erb
<%= form_with(model: notificacione, local: true) do |form| %>
  <% if notificacione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notificacione.errors.count, "error") %> prohibited this notificacione from being saved:</h2>

      <ul>
      <% notificacione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mensaje %>
    <%= form.text_area :mensaje %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.datetime_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :id_tipo_notificacion %>
    <%= form.number_field :id_tipo_notificacion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notificaciones/edit.html.erb
<h1>Editing Notificacione</h1>

<%= render 'form', notificacione: @notificacione %>

<%= link_to 'Show', @notificacione %> |
<%= link_to 'Back', notificaciones_path %>

app/views/notificaciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notificaciones</h1>

<table>
  <thead>
    <tr>
      <th>Mensaje</th>
      <th>Fecha</th>
      <th>Id tipo notificacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notificaciones.each do |notificacione| %>
      <tr>
        <td><%= notificacione.mensaje %></td>
        <td><%= notificacione.fecha %></td>
        <td><%= notificacione.id_tipo_notificacion %></td>
        <td><%= link_to 'Show', notificacione %></td>
        <td><%= link_to 'Edit', edit_notificacione_path(notificacione) %></td>
        <td><%= link_to 'Destroy', notificacione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notificacione', new_notificacione_path %>

app/views/notificaciones/new.html.erb
<h1>New Notificacione</h1>

<%= render 'form', notificacione: @notificacione %>

<%= link_to 'Back', notificaciones_path %>

app/views/notificaciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mensaje:</strong>
  <%= @notificacione.mensaje %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @notificacione.fecha %>
</p>

<p>
  <strong>Id tipo notificacion:</strong>
  <%= @notificacione.id_tipo_notificacion %>
</p>

<%= link_to 'Edit', edit_notificacione_path(@notificacione) %> |
<%= link_to 'Back', notificaciones_path %>